return {
  torkoal = true,
  bagon = true,
  kyogre = true,
  groudon = true,
  rayquaza = false,
  lake_trio = true,
  dialga = true,
  palkia = true,
  regigigas = true,
  stunfisk = true,
  xerneas = true,
  yveltal = true,
  dewpider = true,
  sandygast = true,
  pyukumuku = true,
  cosmog = false,
  toxel = true,
  frigibax = false,
  gmax = false,
  new_megas = true,
}
