return {
  torkoal = true,
  spheal = false,
  bagon = true,
  kyogre = true,
  groudon = true,
  rayquaza = true,
  dialga = true,
  palkia = true,
  dewpider = false,
  sandygast = false,
  pyukumuku = true,
  cosmog = true,
  frigibax = false,
  gmax = false,
}
