[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Add Alolan Raichu's evolution requirement
[[patches]]
[patches.pattern]
target = '=[SMODS Pokermon "pokemon/pokejokers_01.lua"]'
match_indent = true
position = 'before'
pattern = '''
return item_evo(self, card, context, "j_poke_raichu")
'''
payload = '''
if agarmons_config.alolan_raichu then return item_evo(self, card, context, nil) end
'''

# Only show Alolan Raichu's evolution requirement when enabled
[[patches]]
[patches.pattern]
target = '=[SMODS Pokermon "pokemon/pokejokers_01.lua"]'
match_indent = true
position = 'before'
pattern = '''
return {vars = {center.ability.extra.mult, center.ability.extra.money, center.ability.extra.money_threshold}}
'''
payload = '''
if agarmons_config.alolan_raichu then
  return {key = self.key .. '_alolan', vars = {center.ability.extra.mult, center.ability.extra.money, center.ability.extra.money_threshold}}
end
'''
