[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

# Keep Chips/Mult when replaying
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
position = "at"
match_indent = true
pattern = '''
mult = mod_mult(G.GAME.hands[text].mult)
hand_chips = mod_chips(G.GAME.hands[text].chips)
'''
payload = '''
if not G.GAME.agar_replaying_hand then
    mult = mod_mult(G.GAME.hands[text].mult)
    hand_chips = mod_chips(G.GAME.hands[text].chips)
end
'''

# Replay hand
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
position = "after"
match_indent = true
pattern = "G.FUNCS.evaluate_play()"
payload = '''
if AG.effects.should_replay_hand() then
    AG.effects.replay_hand()
end
'''

# Keep played cards for the replay and disable state switching
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
position = "at"
match_indent = true
pattern = '''
        G.FUNCS.draw_from_play_to_discard()
        G.GAME.hands_played = G.GAME.hands_played + 1
        G.GAME.current_round.hands_played = G.GAME.current_round.hands_played + 1
        return true
    end
}))
G.E_MANAGER:add_event(Event({
    trigger = 'immediate',
    func = function()
'''
payload = '''
        if AG.effects.should_replay_hand() then return true end
        G.FUNCS.draw_from_play_to_discard()
        G.GAME.hands_played = G.GAME.hands_played + 1
        G.GAME.current_round.hands_played = G.GAME.current_round.hands_played + 1
        return true
    end
}))
G.E_MANAGER:add_event(Event({
    trigger = 'immediate',
    func = function()
        if AG.effects.should_replay_hand() then return true end
'''
