[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

# Keep Chips/Mult when replaying
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
position = "at"
match_indent = true
pattern = '''
mult = mod_mult(G.GAME.hands[text].mult)
hand_chips = mod_chips(G.GAME.hands[text].chips)
'''
payload = '''
if not G.GAME.agar_replaying_hand then
    mult = mod_mult(G.GAME.hands[text].mult)
    hand_chips = mod_chips(G.GAME.hands[text].chips)
end
'''
