[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Statue code ripped from Ortalab
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
match_indent = true
position = 'after'
pattern = '''
-- TARGET: adding to hand effects
'''
payload = '''
local statue_card_count = AG.effects.get_ortalab_statue_card_count()
if statue_card_count > 0 then
    AG.effects.ortalab_statue_cards = {}
    for i=1, statue_card_count do
        table.insert(final_scoring_hand, G.hand.cards[i])
        table.insert(AG.effects.ortalab_statue_cards, G.hand.cards[i])
    end
end
'''

[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
match_indent = true
position = 'after'
pattern = '''
-- TARGET: effects after hand evaluation
'''
payload = '''
if AG.effects.ortalab_statue_cards then
    for _, card in ipairs(AG.effects.ortalab_statue_cards) do
        highlight_card(card, 1.05, 'down')
    end
    AG.effects.ortalab_statue_cards = nil
end
'''

# Adds Galarian Mr. Mime to Mime Jr.'s evolution
[[patches]]
[patches.pattern]
target = '=[SMODS Pokermon "pokemon/pokejokers_15.lua"]'
position = "before"
match_indent = true
pattern = '''return level_evo(self, card, context, "j_poke_mrmime")'''
payload = '''
if agarmons_config['galarian_mrmime'] and can_evolve(self, card, context, "j_poke_galarian_mrmime") then
  local red_seals, blue_seals = 0, 0
  for k, v in pairs(G.playing_cards) do
    if v.seal == "Red" then red_seals = red_seals + 1 end
    if v.seal == "Blue" then blue_seals = blue_seals + 1 end
  end
  if blue_seals > red_seals
      or (blue_seals == red_seals and pseudorandom("gal_jr_evo") > .50) then
    return level_evo(self, card, context, "j_poke_galarian_mrmime")
  end
end
'''
