[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Store `gengar_rounds` and `trigger` when Gigantamaxing 
[[patches]]
[patches.pattern]
target = '=[SMODS Pokermon "pokemon/pokejokers_04.lua"]'
position = "after"
match_indent = true
pattern = '''name = "gengar",'''
payload = '''poke_custom_values_to_keep = { "gengar_rounds", "trigger" },'''
