[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Add "X turns left" to Joker descriptions
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
position = "after"
match_indent = true
pattern = "_c:generate_ui(info_queue, card, desc_nodes, specific_vars, full_UI_table)"
payload = '''
if _c.rarity == 'agar_gmax' and not pokermon.is_in_collection(card) then
    local turns_left_nodes = AG.gmax.localize_turns_left_desc(card)
    for i, node in ipairs(turns_left_nodes) do
        table.insert(desc_nodes, i, node)
    end
end
'''

# Add `gmax_turns_left` to ability table
[[patches]]
[patches.pattern]
target = "card.lua"
position = "after"
match_indent = true
pattern = "perma_h_x_blind_size = self.ability and self.ability.perma_h_x_blind_size or 0,"
payload = "gmax_turns_left = center.rarity == 'agar_gmax' and AG.gmax.default_duration or nil,"
