[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# [SMODS.calculate_main_scoring] Add scry_view to held in hand scoring effects
[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils.lua"]'
position = "at"
match_indent = true
pattern = '''function SMODS.calculate_main_scoring(context, scoring_hand)
    for _, card in ipairs(context.cardarea.cards) do'''
payload = '''function SMODS.calculate_main_scoring(context, scoring_hand)
    local cards = {}
    for _, card in ipairs(context.cardarea.cards) do
        cards[#cards+1] = card
    end
    if context.cardarea == G.hand and G.scry_hand_effects and G.scry_view then
        for _, scry_card in pairs(G.scry_view.cards) do
            cards[#cards+1] = scry_card
        end
    end
    for _, card in ipairs(cards) do'''

# [SMODS.calculate_end_of_round_effects] Add scry_view to held in hand end of round effects
[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils.lua"]'
position = "at"
match_indent = true
pattern = '''function SMODS.calculate_end_of_round_effects(context)
    for i, card in ipairs(context.cardarea.cards) do'''
payload = '''function SMODS.calculate_end_of_round_effects(context)
    local cards = {}
    for _, card in ipairs(context.cardarea.cards) do
        cards[#cards+1] = card
    end
    if context.cardarea == G.hand and G.scry_hand_effects and G.scry_view then
        for _, scry_card in pairs(G.scry_view.cards) do
            cards[#cards+1] = scry_card
        end
    end
    for i, card in ipairs(cards) do'''
