[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Allow Dynamax Band, Red Orb, and Blue Orbs to be saved from Spectral packs
[[patches]]
[patches.pattern]
target = '=[SMODS Pokermon "pokeui.lua"]'
position = "at"
match_indent = true
pattern = '''if (G.STATE == G.STATES.SMODS_BOOSTER_OPENED and SMODS.OPENED_BOOSTER.label:find("Pocket")) or (G.GAME.poke_save_all and not SMODS.OPENED_BOOSTER.label:find("Wish")) or (card.ability.name == 'megastone') then'''
payload = '''if (G.STATE == G.STATES.SMODS_BOOSTER_OPENED and SMODS.OPENED_BOOSTER.label:find("Pocket")) or (G.GAME.poke_save_all and not SMODS.OPENED_BOOSTER.label:find("Wish")) or (card.ability.name == 'megastone') or (card.ability.name == 'dynamaxband') or (card.ability.name == 'redorb') or (card.ability.name == 'blueorb') then'''
